
%Module qgis.core 0

%Import QtCore/QtCoremod.sip
%Import QtGui/QtGuimod.sip
%Import QtXml/QtXmlmod.sip

// TODO: more files to wrap

%Include qgis.sip
%Include qgsapplication.sip
%Include qgsdataprovider.sip
%Include qgsdatasourceuri.sip
%Include qgslogger.sip
%Include qgspoint.sip
%Include qgsprovidermetadata.sip
%Include qgsproviderregistry.sip
%Include qgsrect.sip
%Include qgsspatialrefsys.sip

