######################################################################
# Automatically generated by qmake (1.06c) Tue Sep 9 19:32:58 2003
######################################################################

TEMPLATE = lib 
CONFIG += debug \
          warn_on \
          qt \
          thread 
INCLUDEPATH += .

# Input
HEADERS += qgsshapefileprovider.h
SOURCES += qgsshapefileprovider.cpp ../qgsfeature.cpp ../qgsfeatureattribute.cpp
